package domain.constant;

public class Constant {
    public final static String LOGIN_URL = "https://api.av.by/auth/login/sign-in";
    public final static String CONTENT_TYPE_HEADER = "Content-Type";
    public final static String SEARCH_ANY_CAR_URL = "https://cars.av.by/filter";
    public final static String SEARCH_CAR_BY_FILTER_URL = "https://api.av.by/offer-types/cars/filters/main/apply";
    public final static String SEARCH_RESULT_RESPONSE_KEY = "seo.canonicalPage.url";
    public final static String SEARCH_CUSTOM_TEXT_QUERY_MULTIROULE = "https://cars.av.by/filter?brands[0][brand]=589&description=%D0%BC%D1%83%D0%BB%D1%8C%D1%82%D0%B8%D1%80%D1%83%D0%BB%D1%8C";
    public final static String SEARCH_BODY_TYPE_CONVERTIBLE = "https://cars.av.by/filter?body_type[0]=7";
    public final static String SEARCH_BY_BRAND_ACURA = "https://cars.av.by/acura";
    public final static  String SEARCH_BY_TRANSMISSION_TYPE_AUTOMATIC = "https://cars.av.by/filter?brands[0][brand]=1&transmission_type=1";
    public final static String FINANCE_SEARCH_URL = "https://api.av.by/finance/products/search";
    public final static String HOME_URL = "https://av.by/";
    public final static String HOME_PAGE_CONTENT_TYPE = "text/html; charset=utf-8";
    public final static String VEHICLE_URL = "https://cars.av.by/";
    public final static String WHEELS_PARTS_URL = "https://parts.av.by/";
    public final static String NEWS_URL = "https://av.by/news";
    public final static String INFO_URL = "https://av.by/pages/info";
    public final static String FINANCE_URL = "https://av.by/finance";
    public final static String VIN_CHECKER_URL = "https://av.by/vin";
    public static final String CAR_BRAND_SEARCH = "Audi Q2";
    public final static String VALID_LOGIN = "platinumfoxirina@gmail.com";
    public final static String VALID_PASSWORD = "qatestteam123";
    public final static String HOME_PAGE_COPYRIGHT = "© 2001, ООО «Автоклассифайд», УНП 192787977, Минск, ул. Кутузова, 15";
    public final static String FINANCE_TITLE = "Кредиты и лизинг на покупку транспорта и комплектующих";
    public final static String VEHICLE_TITLE = "Объявления о продаже автомобилей с пробегом в Беларуси";
    public final static String PART_TITLE = "Продажа запчастей новых и б/у в Беларуси";
    public final static String NEWS_TITLE = "Пишем про авторынок в Беларуси, делаем обзоры, интервью и помогаем людям выбирать себе автомобили";
    public final static String INFO_TITLE = "Знания";
    public final static String VIN_TITLE = "Проверка истории транспорта по VIN";
    public final static String CREDIT_OFFER_TEXT = "Автомобиль с пробегом в лизинг";
    public final static String CREDIT_NEW_CAR_OFFER_TEXT = "На новый авто и с пробегом";
    public final static String CREDIT_TRUCK_OFFER_TEXT = "Кредит на любые цели. Полностью онлайн";
    public final static String LOGIN_SUCCESS_TITLE = "Мои объявления";
    public final static String NEW_OFFER_TITLE = "Новое объявление";
    public final static String LOGIN_NEEDED_TITLE = "Вход";
    public final static String LOGIN_FAILED_INVALID_CREDS_MESSAGE = "Неверный логин или пароль. Если забыли пароль, восстановите его";
    public final static String LOGIN_FAILED_EMPTY_FIELDS_ERROR_MESSAGE = "Заполните оба поля";
    public final static String LOGIN_FAILED_EMPTY_FIELDS_REQUEST_ERROR = "Запрос не соответствует правилам валидации";
    public final static String LOGIN_VALIDATION_FAILED_MESSAGE = "exception.validation.failed";
    public final static String LOGIN_AUTHORIZATION_FAILED_SIGN_MESSAGE = "exception.auth.invalid_sign_in";
    public final static String VIN_CODE_ERROR_FORMAT_MESSAGE = "Неверно указан VIN-номер";
    public final static String VIN_CHECK_SUCCESS_MESSAGE = "Купить отчёт";
    public final static String VIN_CODE_NUMBER_ERROR_MESSAGE = "VIN-номер состоит из 17 символов";
    public final static String VIN_CODE_GLOBAL_ERROR_SCREEN_MESSAGE = "Что-то сломалось";
}
